/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layouts/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layouts/AppHeader.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropDown: typeof import('bootstrap-vue-next')['BDropDown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BDropDownItem: typeof import('bootstrap-vue-next')['BDropDownItem']
    BFormRadio: typeof import('bootstrap-vue-next')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    CalculationResult: typeof import('./src/components/common/CalculationResult.vue')['default']
    Pokemon: typeof import('./src/components/pokemon/Pokemon.vue')['default']
    PokemonHP: typeof import('./src/components/pokemon/left/PokemonHP.vue')['default']
    PokemonLevel: typeof import('./src/components/pokemon/left/PokemonLevel.vue')['default']
    PokemonMain: typeof import('./src/components/pokemon/PokemonMain.vue')['default']
    PokemonSelect: typeof import('./src/components/pokemon/left/PokemonSelect.vue')['default']
    PokemonSkill: typeof import('./src/components/pokemon/right/PokemonSkill.vue')['default']
    PokemonStatInfo: typeof import('./src/components/pokemon/left/PokemonStatInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skill: typeof import('./src/components/pokemon/right/Skill.vue')['default']
  }
}
