/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layouts/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layouts/AppHeader.vue')['default']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropDown: typeof import('bootstrap-vue-next')['BDropDown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BDropDownItem: typeof import('bootstrap-vue-next')['BDropDownItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
